#pragma once

#ifdef _DEBUG
#ifndef MESSAGES_ENABLED
//#define MESSAGES_ENABLED
#endif
#endif

#define LOCAL_ENTITY_INDEX 0

//#include "Console.h"
//Console gConsole;

#include "Vars.h"
CVars gVars;

#include "Vector.h"

#include "AttributeManager.h"
#include "AttributeInfo.h"
#include "Client.h"
#include "World.h"
#include "Entity.h"

bool IsKeyDown(int key)
{
	return (GetAsyncKeyState(key) & 0x8000) != 0;
}

bool WasKeyDown(int key)
{
	return (GetAsyncKeyState(key) & 0x0001) != 0;
}

static const char* GetAttributeStringfromIndex(int index)
{
	static const char* szAttributes[] =
	{
		"AimChangeAccuracyRecoveryTimeMSFinal",
		"AimChangeModifierFinal",
		"AimChangeSensitivityFinal",
		"AimSpreadMaxFinal",
		"AimSpreadMinFinal",
		"AirSupplyFinal",
		"AirSupplyDepletionRateFinal",
		"AirSupplyRegenRateFinal",
		"AirSupplyRegenTickIntervalFinal",
		"AirSupplyDepletionTickIntervalFinal",
		"AirSupplyDamageRateFinal",
		"AirSupplyDamageIntervalFinal",
		"FallDamageModFinal",
		"FallDamageLethalHeightFinal",
		"FallDamageStartHeightFinal",
		"BleedingOutHealthFinal",
		"BleedingOutHealthDegenRateFinal",
		"BleedingOutHealthDegenTickIntervalFinal",
		"BleedingOutDieQuickMultiplierFinal",
		"BleedingOutReviveHealthPercentageFinal",
		"ClipSizeFinal",
		"CoverAimSpreadMaxFinal",
		"CoverAimSpreadMinFinal",
		"CoverSpreadMaxFinal",
		"CoverSpreadMinFinal",
		"CriticalHitChanceResilienceFinal",
		"DamageDoneToSuppressedTargetModFinal",
		"DamageDoneToElitesModFinal",
		"DamageMultiplierArmsFinal",
		"DamageMultiplierBodyFinal",
		"DamageMultiplierHeadFinal",
		"DamageMultiplierLegsFinal",
		"DamageTakenModFinal",
		"DamageTakenFromElitesModFinal",
		"DownedDamageMaxFinal",
		"DownedDamageMaxPVPFinal",
		"DownedDamageModFinal",
		"DownedDamageModPVPFinal",
		"DownedHealthFinal",
		"DownedHealthDegenRateFinal",
		"DownedHealthDegenTickIntervalFinal",
		"DownedInARowMaxFinal",
		"DownedInARowMaxTimePeriodFinal",
		"DownedDieQuickMultiplierFinal",
		"DownedReviveHealthPercentageFinal",
		"TalentDownedAssistSpeedModFinal",
		"TalentSecondChanceHealModFinal",
		"TalentSecondChanceCooldownFinal",
		"HealthFinal",
		"HealthRegenDelayFinal",
		"HealthRegenExitCombatDelayFinal",
		"HealthRegenRateFinal",
		"HealthRegenTickIntervalFinal",
		"HealthSegmentsFinal",
		"HorizontalRecoilBorderLeftFinal",
		"HorizontalRecoilBorderRightFinal",
		"HorizontalRecoilLeftFinal",
		"HorizontalRecoilRecoveryTimeMSFinal",
		"HorizontalRecoilRightFinal",
		"HorizontalRecoilTimeMSFinal",
		"IncomingHealingModFinal",
		"OutgoingHealingModFinal",
		"DarkZoneInventoryFinal",
		"DefaultInventoryFinal",
		"ResourceInventoryFinal",
		"VanityInventoryFinal",
		"BackupSpaceInventoryFinal",
		"StashInventoryFinal",
		"DarkZoneStashInventoryFinal",
		"MailboxInventoryFinal",
		"LifeOnKillFinal",
		"LootChanceModFinal",
		"LootedAmmoModFinal",
		"LootedGoldModFinal",
		"LootMagicFindFinal",
		"MeleeDamagePvPFinal",
		"MeleeDamageFinal",
		"MeleeDamageMitigationPercentageFinal",
		"MovementSpeedModFinal",
		"PitchRecoveryPerSecondFinal",
		"PitchRecoveryPercentFinal",
		"PulseCriticalHitChanceFinal",
		"PulseCriticalHitDamageFinal",
		"PVPDamageModifierFinal",
		"RPMFinal",
		"RangeLongFinal",
		"RangeMaxFinal",
		"RangeOptimalFinal",
		"RecoilBaseFinal",
		"RecoilClimbTimeMSFinal",
		"RecoilIncreasePerBulletFinal",
		"RecoilMaxFinal",
		"RecoilMinFinal",
		"RecoilRecoveryPerSecondFinal",
		"RecoilRecoveryTimeMSFinal",
		"RecoilResetTimeMSFinal",
		"ReloadTimeMSFinal",
		"EmptyClipFirstRoundReloadTimeMSFinal",
		"InitialShellReloadTimeMSFinal",
		"RespawnTimeMSFinal",
		"RespawnMinimumTimeFinal",
		"ReviveDurationMSFinal",
		"ReviveFromDeadDurationMSFinal",
		"ReviveImmunityDurationFinal",
		"ReviveImmunityRangeFinal",
		"ReviveServerNotifyTickIntervalMSFinal",
		"SafetyBeltCooldownFinal",
		"SkillCriticalHitChanceFinal",
		"SkillCriticalHitDamageModFinal",
		"SkillHasteModFinal",
		"SpreadIncreaseSpeedFinal",
		"SpreadIncreaseTimeMSFinal",
		"SpreadMaxFinal",
		"SpreadMinFinal",
		"SpreadMovementModFinal",
		"SpreadReductionSpeedFinal",
		"StaggerDamageModifierFinal",
		"StaminaConsumptionRateFinal",
		"StaminaConsumptionTickIntervalFinal",
		"StaminaDamageTakenModFinal",
		"StaminaFinal",
		"StaminaRegenDelayFinal",
		"StaminaRegenRateFinal",
		"StaminaRegenTickIntervalFinal",
		"SuppressionFinal",
		"TargetOutOfCoverDamageModFinal",
		"ThrowRangeModFinal",
		"TimeToMaxAccuracyMSFinal",
		"TimeToMinAccuracyMSFinal",
		"WeaponCriticalHitChanceFinal",
		"WeaponCriticalHitDamageModFinal",
		"WeaponCriticalHitChanceVsOOCFinal",
		"WeaponDrawSpeedModFinal",
		"WeaponHolsterSpeedModFinal",
		"XPModFinal",
		"YawRecoveryPerSecondFinal",
		"YawRecoveryPercentFinal",
		"ZoneDiscoveryXPFinal",
		"PhysicalDamageMinFinal",
		"PhysicalDamageMaxFinal",
		"PhysicalDamageVariationFinal",
		"BlastDamageMinFinal",
		"BlastDamageMaxFinal",
		"BlastDamageVariationFinal",
		"BleedDamageMinFinal",
		"BleedDamageMaxFinal",
		"BleedDamageVariationFinal",
		"BurnDamageMinFinal",
		"BurnDamageMaxFinal",
		"BurnDamageVariationFinal",
		"ToxinDamageMinFinal",
		"ToxinDamageMaxFinal",
		"ToxinDamageVariationFinal",
		"ElectricDamageMinFinal",
		"ElectricDamageMaxFinal",
		"ElectricDamageVariationFinal",
		"NeutralDamageMinFinal",
		"NeutralDamageMaxFinal",
		"NeutralDamageVariationFinal",
		"EMPDamageMinFinal",
		"EMPDamageMaxFinal",
		"EMPDamageVariationFinal",
		"StaminaDamageMinFinal",
		"StaminaDamageMaxFinal",
		"StaminaDamageVariationFinal",
		"TestDamageScaling",
		"PrimaryOffensiveCalc",
		"WeaponDamageModBonus",
		"WeaponTypeDamageModCalc",
		"NPCArmorFinal",
		"NPCArmorBypassRatioHeadFinal",
		"NPCArmorBypassRatioBodyFinal",
		"NPCArmorDamageModifierFinal",
		"NPCArmorBypassModifierFinal",
		"PhysicalDamageMitigationPercentageFinal",
		"BlastDamageMitigationPercentageFinal",
		"BleedDamageMitigationPercentageFinal",
		"BurnDamageMitigationPercentageFinal",
		"ToxinDamageMitigationPercentageFinal",
		"ElectricDamageMitigationPercentageFinal",
		"NeutralDamageMitigationPercentageFinal",
		"EMPDamageMitigationPercentageFinal",
		"StaminaDamageMitigationPercentageFinal",
		"SelfSourceDamageMitigationPercentageFinal",
		"FriendlySourceDamageMitigationPercentageFinal",
		"NPCSourceDamageMitigationPercentageFinal",
		"OpponentSourceDamageMitigationPercentageFinal",
		"NullSourceDamageMitigationPercentageFinal",
		"WeaponMethodDamageMitigationPercentageFinal",
		"TrapMethodDamageMitigationPercentageFinal",
		"SkillMethodDamageMitigationPercentageFinal",
		"StatusEffectMethodDamageMitigationPercentageFinal",
		"MeleeMethodDamageMitigationPercentageFinal",
		"EnvironmentMethodDamageMitigationPercentageFinal",
		"BleedingStatusResistancePercentageFinal",
		"BlindDeafStatusResistancePercentageFinal",
		"BurningStatusResistancePercentageFinal",
		"ConfusedStatusResistancePercentageFinal",
		"DisruptedStatusResistancePercentageFinal",
		"ShockedStatusResistancePercentageFinal",
		"StaggeredStatusResistancePercentageFinal",
		"SuppressedStatusResistancePercentageFinal",
		"AimSwayMinHorizontalFinal",
		"AimSwayMaxHorizontalFinal",
		"AimSwayMinVerticalFinal",
		"AimSwayMaxVerticalFinal",
		"AimSwaySpeedModifierFinal",
		"VisualDetectionModFinal",
		"VisualStealthModFinal",
		"AudialDetectionModFinal",
		"AudialStealthModFinal",
		"DarkZoneItemsToDropFinal",
		"DarkZoneItemsToDropRogueFinal",
		"DarkZoneConvertXPModFinal",
		"DarkZoneXPModFinal",
		"DarkZoneXPLossModFinal",
		"DarkZoneXPLossRogueModFinal",
		"DarkZoneXPLossFinal",
		"DarkZoneXPLossRogueFinal",
		"ThreatPerBulletFinal",
		"ThreatTotalGeneratedModFinal",
		"SuppressionTriggerScoreFinal",
		"SuppressionDefenseModifierFinal",
		"SuppressionDepletionRateFinal",
		"SuppressionDurationFinal",
		"SuppressionBufferScoreFinal",
		"SuppressionBufferResetTimeFinal",
		"StaggerGaugeFinal",
		"StaggerAnimationDurationModFinal",
		"ChanceOfGreenToBlueWhenCraftingFinal",
		"ChanceOfBlueToPurpleWhenCraftingFinal",
		"ChanceOfPurpleToOrangeWhenCraftingFinal",
		"XPRepeatableEventsModFinal",
		"CreditsRepeatableEventsModFinal",
		"SecurityRepeatableEventsModFinal",
		"PersonnelRescueMissionsModFinal",
		"SupplyDropMissionsModFinal",
		"XPHeadshotKillsModFinal",
		"XPTacticalKillsModFinal",
		"XPSpecialKillsModFinal",
		"XPEliteKillsModFinal",
		"XPMultiKillsModFinal",
		"XPKillsModFinal",
		"XPAccoladeModFinal",
		"ExtractionTimeModFinal",
		"CraftingCostModFinal",
		"SkillXPModFinal",
		"DZRewardedCredsModFinal",
		"VendorCostModFinal",
		"AmmoDroppedModFinal",
		"CreditsDroppedModFinal",
		"LootedCreditsModFinal",
		"LootedDZCreditsModFinal",
		"UnlockedSkillSlotsFinal",
		"SecondaryWeaponAllowedBoolFinal",
		"RewardedCredsModFinal",
		"PerkAutoDiscoverFinal",
		"LastBulletDamageModFinal",
		"PrimaryDefensiveFinal",
		"PrimaryOffensiveFinal",
		"PrimarySupportFinal",
		"OverHealFinal",
		"OverHealDepletionDelayFinal",
		"OverHealDepletionRateFinal",
		"SignatureSkillResourceRewardModFinal",
		"CombatBuff_Cooldown_Final",
		"DefenceBuff_Cooldown_Final",
		"GroupHeal_Cooldown_Final",
		"ModSocketAttributeBonus",
		"ArmorMitigationDefaultRatingFlatBonus",
		"ContaminationZoneGasMaskLevelDefaultFlatBonus",
		"DefaultInventoryFlatBonus",
		"WeaponDamageBaseModBonus",
		"PrimaryOffensiveFlatBonus",
		"PrimaryDefensiveFlatBonus",
		"PrimarySupportFlatBonus",
		"AmmoIncendiaryFinal",
		"AmmoExplosiveFinal",
		"ApplyStatusBurnPercentageFinal",
		"ApplyExplosionConsumablePercentageFinal",
		"ArmorRatingUI",
		"DefaultInventoryUI",
		"ContaminationProtectionUI",
		"WeaponDamageCompareUI",
		"WeaponRPMCompareUI",
		"WeaponMagazineCompareUI",
		"WeaponAccuracyCompareUI",
		"WeaponRangeCompareUI",
		"WeaponReloadTimeCompareUI",
		"WeaponStabilityCompareUI"
	};

	if (index < AttributeManager::AtributeIndexMax)
		return szAttributes[index];
	return "<unknown>";
}